import {storage} from '@/adapters/storage'; import {tickets,equipment,employees,maintenance,inventory} from '@/mocks'; import type {Ticket,Equipment,Employee,Maintenance,InventoryItem,User} from '@/types'
import {moduleSeeds,type ModuleRecord} from '@/mocks/modules'
import {ref} from 'vue'
import {normalizeModule,validateModule} from './modules'
const revision=ref(0)
const copy=<T>(value:T):T=>JSON.parse(JSON.stringify(value))
const author=()=>storage.get<User|null>('session',null)?.name||'Equipe de TI'
export const StorageService=storage
export const ModuleService={list(kind:string){revision.value;return storage.get<ModuleRecord[]>(`module:${kind}`,copy(moduleSeeds[kind]||[])).map(item=>normalizeModule(kind,item))},save(kind:string,items:ModuleRecord[]){items.forEach(item=>validateModule(kind,item));storage.set(`module:${kind}`,items.map(item=>normalizeModule(kind,item)));revision.value++},find(kind:string,id:number){return this.list(kind).find(x=>x.id===id)}}
export const TicketService={list(){return storage.get('tickets',copy(tickets))},nextIdentity(){const all=this.list(),previous=storage.get('ticketSequence',{id:0,protocol:248});const next={id:Math.max(previous.id,0,...all.map(t=>t.id))+1,protocol:Math.max(previous.protocol,248,...all.map(t=>Number(t.protocol.replace(/^TI-/,''))||0))+1};storage.set('ticketSequence',next);return{id:next.id,protocol:`TI-${String(next.protocol).padStart(4,'0')}`}},create(ticket:Ticket){const all=this.list();if(all.some(t=>t.id===ticket.id||t.protocol===ticket.protocol))throw new Error('Identificador de chamado já utilizado.');storage.set('tickets',[ticket,...all]);return ticket},update(id:number,patch:Partial<Ticket>){const all=this.list(),current=all.find(t=>t.id===id);if(!current)throw new Error('Chamado não encontrado.');const at=new Date().toISOString(),changes:string[]=[];for(const [key,label] of [['status','Status'],['priority','Prioridade'],['technician','Técnico']] as const){if(patch[key]!==undefined&&patch[key]!==current[key])changes.push(`${label}: ${current[key]} → ${patch[key]}`)}const updated={...current,...patch,id:current.id,protocol:current.protocol,updatedAt:at};if(patch.status&&patch.status!==current.status)updated.resolvedAt=patch.status==='Resolvido'?at:undefined;updated.history=[...(patch.history||current.history||[]),...changes.map(description=>({id:crypto.randomUUID(),author:author(),description,at}))];storage.set('tickets',all.map(t=>t.id===id?updated:t));return updated},remove(id:number){storage.set('tickets',this.list().filter(t=>t.id!==id))},find(id:number){return this.list().find(t=>t.id===id)}}
export const EquipmentService={list(){revision.value;return storage.get<Equipment[]>('equipment',copy(equipment))},save(items:Equipment[]){const codes=new Set<string>();for(const item of items){const code=item.code.trim().toUpperCase();if(!code||!item.name.trim())throw new Error('Informe código e nome do equipamento.');if(codes.has(code))throw new Error(`Código ${code} já cadastrado.`);codes.add(code)}storage.set('equipment',items);revision.value++},find(id:number){return this.list().find(e=>e.id===id)}}
export const EmployeeService={list:()=>ModuleService.list('employees')}
export const MaintenanceService={list:()=>ModuleService.list('maintenance')}
export const InventoryService={list:()=>ModuleService.list('inventory')}
export const AuthService={login(email:string,password:string):User{if(email!=='admin@aeroti.local'||password!=='admin123')throw new Error('E-mail ou senha inválidos. Confira as credenciais.');return storage.get<User>('profile',{id:1,name:'Lucas Almeida',email,role:'Gestor de TI',department:'Tecnologia da Informação',unit:'Aeroclube de Juiz de Fora'})},logout(){storage.remove('session')}}
export const NotificationService={permission:()=>Promise.resolve('granted' as NotificationPermission)}
export const FileService={pick:()=>Promise.resolve([{name:'anexo-simulado.pdf',size:184000}]),openDataDirectory:()=>Promise.resolve('Ação disponível na versão desktop')}
export const WhatsAppService={send:async(_phone:string,_message:string)=>({id:`mock-${Date.now()}`,status:'sent'}),simulateProtocol:()=>`TI-${Math.floor(250+Math.random()*50)}`}
export const EmailService={send:async(_email:string,_message:string)=>({id:`email-${Date.now()}`,status:'sent'})}
export const ReportService={async exportPdf(title:string,headers:string[],rows:(string|number)[][]){const {jsPDF}=await import('jspdf');const pdf=new jsPDF();pdf.setFontSize(16);pdf.text(`AeroTI - ${title}`,14,18);pdf.setFontSize(9);pdf.text(`Gerado em ${new Date().toLocaleString('pt-BR')}`,14,25);let y=34;pdf.setFont('helvetica','bold');pdf.text(headers.join('  |  ').slice(0,110),14,y);pdf.setFont('helvetica','normal');for(const row of rows){y+=7;if(y>280){pdf.addPage();y=18}pdf.text(row.map(String).join('  |  ').slice(0,120),14,y)}pdf.save(`aeroti-${title.toLowerCase().replaceAll(' ','-')}.pdf`)}}
export const ApiClient={baseUrl:import.meta.env.VITE_API_BASE_URL||'/api',async request(){throw new Error('Backend Laravel ainda não conectado')}}
